#!/usr/bin/env bash

system_type=$(uname -s)
architecture=$(uname -m)

# Make sure we are in ${HOME}
cd "${HOME}"

echo ">>> Init submodules"
yadm submodule update --recursive --init

# Check if we are on Linux
if [[ "${system_type}" = "Linux" ]]; then

	# Set the default shell to bash
	echo ">>> Setting shell to bash..."
	chsh -s /bin/bash "${USER}"

fi

# Check if we are on a Mac
if [[ "$system_type" = "Darwin" ]]; then

	# Check if we are on an Arm device
	if [[ architecture = "arm64" ]]; then

		# Disable the delay when showing and hiding the Dock
		defaults write com.apple.dock autohide-delay -float 0 && defaults write com.apple.dock autohide-time-modifier -float 0.4 && killall Dock

	fi

	# Make sure we have homebrew
	if ! command -v brew >/dev/null 2>&1; then
		echo "ERROR: Homebrew is not installed. Please install it first."
		exit 1
	fi

	# Make sure $HOMEBREW_PREFIX is Set
	HOMEBREW_PREFIX="$(brew --prefix)"

	# install brew packages
	if [[ -f "${HOME}/.Brewfile" ]]; then
		echo ">>> Applying .Brewfile..."
		brew bundle install --global
	fi

	# Make lists of installed packages
	INSTALLED_FORMULA=$(brew list -1 --formula)
	INSTALLED_CASK=$(brew list -1 --cask)

	# Change default shell to bash (homebrew bash)
	if [[ ${INSTALLED_FORMULA} =~ "bash" ]]; then
		echo ">>> Setting shell to \"${HOMEBREW_PREFIX}/bin/bash\" ..."
		sudo chsh -s "${HOMEBREW_PREFIX}/bin/bash" ${USER} >/dev/null 2>&1
	else
		echo ">>> WARNING: Did not find bash in installed formulae!"
		echo ">>> Falling back to \"/bin/bash\" ..."
		chsh -s "/bin/bash" "${USER}"
	fi

	# Link bash-completion
	if [[ ${INSTALLED_FORMULA} =~ "bash-completion" ]]; then
		echo ">>> Linking bash-completion..."
		brew completions link >/dev/null 2>&1
	fi

	# Set custom iTerm2 config path
	if [[ ${INSTALLED_CASK} =~ "iterm2" ]]; then
		echo ">>> Setting iTerm prefs directory..."
		defaults write com.googlecode.iterm2 PrefsCustomFolder "${HOME}/.iterm2" >/dev/null 2>&1
		defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true >/dev/null 2>&1
	fi
fi

# Done!
echo "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┃                                          ┃"
echo "┃  ✔  All done!                            ┃"
echo "┃                                          ┃"
echo "┃  Please restart your terminal session.   ┃"
echo "┃                                          ┃"
echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"
