#!/bin/bash

system_type=$(uname -s)

# Make sure we are in ${HOME}
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

# Check if we are on a Mac
if [ "$system_type" = "Darwin" ]; then

	# install homebrew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
		echo "Installing homebrew"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi

	# install all the things
	if [ -f "$HOME/.Brewfile" ]; then
		echo "Updating homebrew bundle"
		brew bundle install --global
	fi

	# Set custom iTerm2 config path
	if [ -d "$HOME/.iterm2" ]; then
		echo ">>> Setting iTerm prefs directory.."
		defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
		defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
	fi

fi
